### ISSUE TITLE
Error executing vim.schedule lua callback: vim/shared.lua:219: after the second argument: expected table, got nil

### ISSUE THREAD

**Issue by binnz** [ChristianChiarulli/LunarVim#808] opened 2021-07-09 09:46 UTC
when use Tab to show code autocomplete, error below occurs, how to fix this.
```
Error executing vim.schedule lua callback: vim/shared.lua:219: after the second argument: expected table, got nil
stack traceback:
        vim/shared.lua:219: in function 'tbl_deep_extend'
        ...pack/packer/opt/nvim-compe/lua/compe_nvim_lsp/source.lua:106: in function '_create_document'
        ...pack/packer/opt/nvim-compe/lua/compe_nvim_lsp/source.lua:89: in function 'documentation'
        ...vim/site/pack/packer/opt/nvim-compe/lua/compe/source.lua:224: in function 'callback'
        ...ite/pack/packer/opt/nvim-compe/lua/compe/utils/async.lua:85: in function 'callback'
        ...vim/site/pack/packer/opt/nvim-compe/lua/compe/source.lua:209: in function 'callback'
        ...pack/packer/opt/nvim-compe/lua/compe_nvim_lsp/source.lua:67: in function 'resolve'
        ...vim/site/pack/packer/opt/nvim-compe/lua/compe/source.lua:205: in function 'resolve'
        ...vim/site/pack/packer/opt/nvim-compe/lua/compe/source.lua:221: in function 'documentation'
        ...site/pack/packer/opt/nvim-compe/lua/compe/completion.lua:99: in function 'callback'
        ...ite/pack/packer/opt/nvim-compe/lua/compe/utils/async.lua:85: in function <...ite/pack/packer/opt/nvim-compe/lua/compe/utils/async.lua:81>
```

**Comment by abzcoding** [comment] 2021-07-14 08:07
@binnz we've overhauled the auto-completion, can you pull the latest changes from `master` or `rolling` and check if the issue is resolved or not?

**Comment by rebuilt** [comment] 2021-07-26 18:23
This issue has been resolved in rolling.  Please reopen if you're still getting errors

**Closed by rebuilt** 2021-07-26 18:23 UTC
