### ISSUE TITLE
[Bug]: Latex _ and ^ giving very weird parsing

### ISSUE THREAD

**Issue by atropos112** [ChristianChiarulli/LunarVim#708] opened 2021-07-05 16:44 UTC
### Problem description

1. Fresh install
2. Run :PackerCompile and :PackerInstall
3. Open a tex file with "_" and "^" 

I have installed fresh and treesitter (?) seems to be having a tantrum. The latex write up is fine, no errors but every subscript and superscript is highlighted red suggesting an error of sorts. Any idea how to fix/disable this ?

### LunarVim version

Master - Up to date

### Neovim version (>= 0.5)

0.5.0-1

### Screenshots

![image](https://user-images.githubusercontent.com/33070637/124500643-09055f00-ddb8-11eb-966b-8dd2216e081b.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by PZ31k0nauT** [comment] 2021-07-05 17:29
Yeah I have the problem with treesitter as well. The problem is that it is not implemented in the latex-lsp (texlab). The maintainer wrote this in an issue (https://github.com/latex-lsp/texlab/issues/405#issuecomment-831472533).
I don't know if it is possible to disable treesitter if a tex file is being used.

**Comment by atropos112** [comment] 2021-07-05 17:55
I receive this issue regardless if `:LspInstall latex` is issued or not, as such I thought Lsp is not the issue.

Treesitter on the other hand I'm not sure how to disable for latex and not other languages.

**Comment by atropos112** [comment] 2021-07-05 20:07
I have removed everything including configs, removed cache etc and now it works. I am unsure why it started working but i guess that resolves the issue.

**Comment by atropos112** [comment] 2021-07-06 13:46
Okay, I have changed literally nothing (with nvim that is) and after 18 hours or so the same issue is back.

**Comment by PZ31k0nauT** [comment] 2021-07-07 06:13
I tested your equation. No problems on my side. But I'm on PR #671 (shameless plug).

First I thought it could be spell check. In the past spell check gave me this glaring red background. Maybe test it with switching spell check off.

Then I thought that the syntax highlighting is the culprit. But it wouldn't explain all of those weird highlights.

Which version of LunarVim do you have installed? Is neoformat implemented?

Furhtermore it might be useful to check the installed version of texlab.

Tastyep wrote how to look it up: 
https://github.com/ChristianChiarulli/LunarVim/pull/671#issuecomment-874213325

**Comment by atropos112** [comment] 2021-07-07 20:46
> I tested your equation. No problems on my side. But I'm on PR #671 (shameless plug).
> 
> First I thought it could be spell check. In the past spell check gave me this glaring red background. Maybe test it with switching spell check off.
> 
> Then I thought that the syntax highlighting is the culprit. But it wouldn't explain all of those weird highlights.
> 
> Which version of LunarVim do you have installed? Is neoformat implemented?
> 
> Furhtermore it might be useful to check the installed version of texlab.
> 
> Tastyep wrote how to look it up:
> [#671 (comment)](https://github.com/ChristianChiarulli/LunarVim/pull/671#issuecomment-874213325)

I am sure it is not the particular equation I wrote, I even tried stuff as basic as 
```
\begin{align}
2^2_2
\end{align}
```
and I still see the weird marking, with spacegray theme they are much less distracting, either way they shouldn't be there. How do I turn spellcheck off ? I am using the most recent (Master) LunarVim with no extra plugins. I havent seen neoformat being part of LunarVim by default so i am probably not using it, I didn't set it up for sure.

**Comment by rebuilt** [comment] 2021-07-07 20:54
I use escape to clear any highlighting.  I have this keybond set up in my config.  https://github.com/ChristianChiarulli/LunarVim/pull/656/files

**Comment by rebuilt** [comment] 2021-07-07 20:57
I experienced weird highlighting as well.  I had to update my version of neovim

**Comment by atropos112** [comment] 2021-07-07 21:24
From what I see I have two options neovim (0.5.0-1) for which I have the highlighting issue or neovim-nightly-git (0.5.0.r1353.g0a653f7ab-1) for which I have #627 issu and there neovim refuses to load anything so I feel that neovim  (0.5.0-1) is the only functioning choice for me.

Pressing escape doesn't do anything with highlights, is it possible to turn off highlight of this kind entirely for .tex files only?

**Comment by PZ31k0nauT** [comment] 2021-07-07 22:20
So you're kind of in a dependency hell.

I for my part am on neovim (0.6.0-dev+62d67de) and have no problems what so ever with the syntax highlighting of your equation.

If you want to tell spellchecking of you have to type `:set nospell`.

With lunarvim you can also try `<leader>h`.

With `:help highlight` I came across `:so $VIMRUNTIME/syntax/hitest.vim` which should be called when a tex file is focused. But to be honest I don't know how helpful that information will be.

**Comment by atropos112** [comment] 2021-07-07 23:03
Dependency hell what a great name haha. I completely forgot nvim 0.6N was a thing now, tried it just now (nvim v0.6.0-dev+14-gdf33f30e8), same highlighting issues, sadly. I tried `:set nospell` and `<leader>h` and the weird highlight is still haunting me sadly. I am not sure what `:so $VIMRUNTIME/syntax/hitest.vim ` was meant to do, from what I gather it gives a list under what error what highlight happens but the number of possible errors for this highlight is veryyy long

```
	Error NvimInvalid NvimInvalidAssignment
	NvimInvalidPlainAssignment
	NvimInvalidAugmentedAssignment
	NvimInvalidAssignmentWithAddition
	NvimInvalidAssignmentWithSubtraction
	NvimInvalidAssignmentWithConcatenation
	NvimInvalidOperator NvimInvalidUnaryOperator
	NvimInvalidUnaryPlus NvimInvalidUnaryMinus
	NvimInvalidNot NvimInvalidBinaryOperator
	NvimInvalidComparison
	NvimInvalidComparisonModifier
	NvimInvalidBinaryPlus NvimInvalidBinaryMinus
	NvimInvalidConcat NvimInvalidConcatOrSubscript
	NvimInvalidOr NvimInvalidAnd
	NvimInvalidMultiplication NvimInvalidDivision
	NvimInvalidMod NvimInvalidTernary
	NvimInvalidTernaryColon NvimInvalidDelimiter
	NvimInvalidParenthesis NvimInvalidLambda
	NvimInvalidNestingParenthesis
	NvimInvalidCallingParenthesis
	NvimInvalidSubscript NvimInvalidSubscriptBracket
	NvimInvalidSubscriptColon NvimInvalidCurly
	NvimInvalidContainer NvimInvalidDict
	NvimInvalidList NvimInvalidValue
	NvimInvalidIdentifier NvimInvalidIdentifierScope
	NvimInvalidIdentifierScopeDelimiter
	NvimInvalidIdentifierName
	NvimInvalidIdentifierKey NvimInvalidColon
	NvimInvalidComma NvimInvalidArrow
	NvimInvalidRegister NvimInvalidNumber
	NvimInvalidFloat NvimInvalidNumberPrefix
	NvimInvalidOptionSigil NvimInvalidOptionName
	NvimInvalidOptionScope
	NvimInvalidOptionScopeDelimiter
	NvimInvalidEnvironmentSigil
	NvimInvalidEnvironmentName NvimInvalidString
	NvimInvalidStringQuote NvimInvalidSingleQuote
	NvimInvalidDoubleQuote
	NvimInvalidDoubleQuotedUnknownEscape
	NvimInvalidFigureBrace
	NvimDoubleQuotedUnknownEscape texError
	texMathError texBadMath texOnlyMath
	texMathDelimBad qfError
```

**Comment by rafamadriz** [comment] 2021-07-12 18:42
Closing since the problem is not with LunarVim config.

**Closed by rafamadriz** 2021-07-12 18:42 UTC
Labels: bug
