### ISSUE TITLE
[Bug]: Installation script stuck on OK to remove?

### ISSUE THREAD

**Issue by lakshyarao22** [ChristianChiarulli/LunarVim#838] opened 2021-07-10 13:24 UTC
### Problem description

I tried installing lunar vim using one command install, it stuck on OK to remove? [y/N]
even if i type y or n it stuck on the command

### LunarVim version

0.4.7

### Neovim version (>= 0.5)

0.5

### Relevant log output

```shell
health#which_key#check
========================================================================
## WhichKey: checking conflicting keymaps
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"<leader>a"**
  - INFO: rhs: ` `

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (e85a279cf29da1b08648e27214dda20a841e57c8) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.4.2 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - ledger         ✓ . ✓ ✓ ✓ 
  - ocaml          ✓ ✓ ✓ . ✓ 
  - julia          ✓ ✓ ✓ ✓ ✓ 
  - comment        ✓ . . . . 
  - ocaml_interface✓ ✓ ✓ . ✓ 
  - ocamllex       ✓ . . . ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - swift          . . . . . 
  - c_sharp        ✓ . ✓ . ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - scala          . . . . . 
  - supercollider  ✓ ✓ ✓ ✓ ✓ 
  - hcl            ✓ . ✓ . ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - glimmer        ✓ . . . . 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - vue            ✓ . ✓ . ✓ 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - nix            ✓ ✓ ✓ . ✓ 
  - r              ✓ ✓ . . . 
  - bash           ✓ ✓ ✓ . ✓ 
  - rst            ✓ ✓ . . ✓ 
  - fennel         ✓ ✓ . . ✓ 
  - teal           ✓ ✓ ✓ ✓ ✓ 
  - regex          ✓ . . . . 
  - verilog        ✓ ✓ ✓ . ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - dart           ✓ ✓ . ✓ ✓ 
  - elm            . . . . . 
  - elixir         ✓ ✓ . ✓ ✓ 
  - graphql        ✓ . . ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - kotlin         ✓ . . . ✓ 
  - latex          ✓ . ✓ . ✓ 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - beancount      ✓ . ✓ . . 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - bibtex         ✓ . ✓ ✓ . 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - fortran        ✓ . ✓ ✓ . 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - cmake          ✓ . ✓ . . 
  - zig            ✓ ✓ ✓ ✓ ✓ 
  - turtle         ✓ ✓ ✓ ✓ ✓ 
  - gdscript       ✓ ✓ . . ✓ 
  - svelte         ✓ . ✓ ✓ ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - scss           ✓ . . ✓ . 
  - clojure        ✓ ✓ ✓ . ✓ 
  - ql             ✓ ✓ . ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - commonlisp     ✓ ✓ ✓ . . 
  - gomod          ✓ . . . . 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - jsdoc          ✓ . . . . 
  - cuda           ✓ ✓ ✓ ✓ . 
  - sparql         ✓ ✓ ✓ ✓ ✓ 
  - dockerfile     ✓ . . . ✓ 
  - erlang         . . . . . 
  - devicetree     ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

health#lspconfig#check
========================================================================
## Checking language server protocol configuration

health#compe#check
========================================================================
## compe:snippet
  - INFO: snippet engine is not detected.

## compe:mapping
  - INFO: `compe#complete` is not mapped
  - INFO: `compe#confirm` is not mapped
  - INFO: `compe#close` is not mapped
  - INFO: `compe#scroll` is not mapped

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.9 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.9.6
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: panes  ^[[31m███^[[1m▄^[[0m  ^[[32m███^[[1m▄^[[0m  ^[[33m███^[[1m▄^[[0m  ^[[34m███^[[1m▄^[[0m  ^[[35m███^[[1m▄^[[0m  ^[[36m███^[[1m▄^[[0m  ^[[37m███^[[1m▄^[[0m   ^[[31m███^[[1m█^[[0m  ^[[32m███^[[1m█^[[0m  ^[[33m███^[[1m█^[[0m  ^[[34m███^[[1m█^[[0m  ^[[35m███^[[1m█^[[0m  ^[[36m███^[[1m█^[[0m  ^[[37m███^[[1m█^[[0m   ^[[31m███^[[1m█^[[0m  ^[[32m███^[[1m█^[[0m  ^[[33m███^[[1m█^[[0m  ^[[34m███^[[1m█^[[0m  ^[[35m███^[[1m█^[[0m  ^[[36m███^[[1m█^[[0m  ^[[37m███^[[1m█^[[0m   ^[[1m^[[31m ▀▀▀   ^[[32m▀▀▀   ^[[33m▀▀▀   ^[[34m▀▀▀   ^[[35m▀▀▀   ^[[36m▀▀▀   ^[[37m▀▀▀  v16.4.2
  - WARNING: Nvim node.js host does not support panes  ^[[31m███^[[1m▄^[[0m  ^[[32m███^[[1m▄^[[0m  ^[[33m███^[[1m▄^[[0m  ^[[34m███^[[1m▄^[[0m  ^[[35m███^[[1m▄^[[0m  ^[[36m███^[[1m▄^[[0m  ^[[37m███^[[1m▄^[[0m   ^[[31m███^[[1m█^[[0m  ^[[32m███^[[1m█^[[0m  ^[[33m███^[[1m█^[[0m  ^[[34m███^[[1m█^[[0m  ^[[35m███^[[1m█^[[0m  ^[[36m███^[[1m█^[[0m  ^[[37m███^[[1m█^[[0m   ^[[31m███^[[1m█^[[0m  ^[[32m███^[[1m█^[[0m  ^[[33m███^[[1m█^[[0m  ^[[34m███^[[1m█^[[0m  ^[[35m███^[[1m█^[[0m  ^[[36m███^[[1m█^[[0m  ^[[37m███^[[1m█^[[0m   ^[[1m^[[31m ▀▀▀   ^[[32m▀▀▀   ^[[33m▀▀▀   ^[[34m▀▀▀   ^[[35m▀▀▀   ^[[36m▀▀▀   ^[[37m▀▀▀  v16.4.2

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

health#treesitter#check
========================================================================
## Checking treesitter configuration
  - INFO: Runtime ABI version : 13
  - OK: Loaded parser for bash: ABI version 13
  - OK: Loaded parser for beancount: ABI version 13
  - OK: Loaded parser for bibtex: ABI version 13
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for c_sharp: ABI version 13
  - OK: Loaded parser for clojure: ABI version 13
  - OK: Loaded parser for cmake: ABI version 13
  - OK: Loaded parser for comment: ABI version 13
  - OK: Loaded parser for commonlisp: ABI version 13
  - OK: Loaded parser for cpp: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for cuda: ABI version 13
  - OK: Loaded parser for dart: ABI version 13
  - OK: Loaded parser for devicetree: ABI version 13
  - OK: Loaded parser for dockerfile: ABI version 13
  - OK: Loaded parser for elixir: ABI version 13
  - OK: Loaded parser for elm: ABI version 13
  - OK: Loaded parser for erlang: ABI version 13
  - OK: Loaded parser for fennel: ABI version 13
  - OK: Loaded parser for fish: ABI version 13
  - OK: Loaded parser for fortran: ABI version 13
  - OK: Loaded parser for gdscript: ABI version 13
  - OK: Loaded parser for glimmer: ABI version 13
  - OK: Loaded parser for go: ABI version 13
  - OK: Loaded parser for gomod: ABI version 13
  - OK: Loaded parser for graphql: ABI version 13
  - OK: Loaded parser for hcl: ABI version 13
  - OK: Loaded parser for html: ABI version 13
  - OK: Loaded parser for java: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for jsdoc: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for jsonc: ABI version 13
  - OK: Loaded parser for julia: ABI version 13
  - OK: Loaded parser for kotlin: ABI version 13
  - OK: Loaded parser for latex: ABI version 13
  - OK: Loaded parser for ledger: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for nix: ABI version 13
  - OK: Loaded parser for ocaml: ABI version 13
  - OK: Loaded parser for ocaml_interface: ABI version 13
  - OK: Loaded parser for ocamllex: ABI version 13
  - OK: Loaded parser for php: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for ql: ABI version 13
  - OK: Loaded parser for query: ABI version 13
  - OK: Loaded parser for r: ABI version 13
  - OK: Loaded parser for regex: ABI version 13
  - OK: Loaded parser for rst: ABI version 13
  - OK: Loaded parser for ruby: ABI version 13
  - OK: Loaded parser for rust: ABI version 13
  - OK: Loaded parser for scala: ABI version 13
  - OK: Loaded parser for scss: ABI version 13
  - OK: Loaded parser for sparql: ABI version 13
  - OK: Loaded parser for supercollider: ABI version 13
  - OK: Loaded parser for svelte: ABI version 13
  - OK: Loaded parser for swift: ABI version 13
  - OK: Loaded parser for teal: ABI version 13
  - OK: Loaded parser for toml: ABI version 13
  - OK: Loaded parser for tsx: ABI version 13
  - OK: Loaded parser for turtle: ABI version 13
  - OK: Loaded parser for typescript: ABI version 13
  - OK: Loaded parser for verilog: ABI version 13
  - OK: Loaded parser for vue: ABI version 13
  - OK: Loaded parser for yaml: ABI version 13
  - OK: Loaded parser for zig: ABI version 13
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for bash: ABI version 13
  - OK: Loaded parser for beancount: ABI version 13
  - OK: Loaded parser for bibtex: ABI version 13
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for c_sharp: ABI version 13
  - OK: Loaded parser for clojure: ABI version 13
  - OK: Loaded parser for cmake: ABI version 13
  - OK: Loaded parser for comment: ABI version 13
  - OK: Loaded parser for commonlisp: ABI version 13
  - OK: Loaded parser for cpp: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for cuda: ABI version 13
  - OK: Loaded parser for dart: ABI version 13
  - OK: Loaded parser for devicetree: ABI version 13
  - OK: Loaded parser for dockerfile: ABI version 13
  - OK: Loaded parser for elixir: ABI version 13
  - OK: Loaded parser for elm: ABI version 13
  - OK: Loaded parser for erlang: ABI version 13
  - OK: Loaded parser for fennel: ABI version 13
  - OK: Loaded parser for fish: ABI version 13
  - OK: Loaded parser for fortran: ABI version 13
  - OK: Loaded parser for gdscript: ABI version 13
  - OK: Loaded parser for glimmer: ABI version 13
  - OK: Loaded parser for go: ABI version 13
  - OK: Loaded parser for gomod: ABI version 13
  - OK: Loaded parser for graphql: ABI version 13
  - OK: Loaded parser for hcl: ABI version 13
  - OK: Loaded parser for html: ABI version 13
  - OK: Loaded parser for java: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for jsdoc: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for jsonc: ABI version 13
  - OK: Loaded parser for julia: ABI version 13
  - OK: Loaded parser for kotlin: ABI version 13
  - OK: Loaded parser for latex: ABI version 13
  - OK: Loaded parser for ledger: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for nix: ABI version 13
  - OK: Loaded parser for ocaml: ABI version 13
  - OK: Loaded parser for ocaml_interface: ABI version 13
  - OK: Loaded parser for ocamllex: ABI version 13
  - OK: Loaded parser for php: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for ql: ABI version 13
  - OK: Loaded parser for query: ABI version 13
  - OK: Loaded parser for r: ABI version 13
  - OK: Loaded parser for regex: ABI version 13
  - OK: Loaded parser for rst: ABI version 13
  - OK: Loaded parser for ruby: ABI version 13
  - OK: Loaded parser for rust: ABI version 13
  - OK: Loaded parser for scala: ABI version 13
  - OK: Loaded parser for scss: ABI version 13
  - OK: Loaded parser for sparql: ABI version 13
  - OK: Loaded parser for supercollider: ABI version 13
  - OK: Loaded parser for svelte: ABI version 13
  - OK: Loaded parser for swift: ABI version 13
  - OK: Loaded parser for teal: ABI version 13
  - OK: Loaded parser for toml: ABI version 13
  - OK: Loaded parser for tsx: ABI version 13
  - OK: Loaded parser for turtle: ABI version 13
  - OK: Loaded parser for typescript: ABI version 13
  - OK: Loaded parser for verilog: ABI version 13
  - OK: Loaded parser for vue: ABI version 13
  - OK: Loaded parser for yaml: ABI version 13
  - OK: Loaded parser for zig: ABI version 13
```

### Screenshots

![Screenshot_2021-07-10-03_959x396](https://user-images.githubusercontent.com/5268175/125164451-e4422a80-e1af-11eb-9674-d33c4c6aeb36.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment] 2021-07-10 13:43
duplicate of #836

**Closed by abzcoding** 2021-07-10 13:43 UTC
Labels: bug
