### ISSUE TITLE
[Bug]: Weird lines drawn on indent of HTML when cursor moves past

### ISSUE THREAD

**Issue by chuckmasucci** [ChristianChiarulli/LunarVim#740] opened 2021-07-06 22:09 UTC
### Problem description

When moving the cursor over the lines of any HTML, including Vue template HTML, a weird line/double line is drawn seemingly random. Going up and down quickly will change these lines and making an edit to the markup removes them, but they always come back as the cursor again scroll past them.

I am sure it's a plugin causing this, but am having trouble pinpoint it.

Thanks!

https://user-images.githubusercontent.com/1163251/124672431-e2086500-de6b-11eb-9c19-de5fea9bb035.mp4

### LunarVim version

Master

### Neovim version (>= 0.5)

NVIM v0.5.0

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by ChristianChiarulli** [comment] 2021-07-06 23:25
hmm I used to see similar behavior with the indentline plugin, I'll take a look soon.

**Comment by chuckmasucci** [comment] 2021-07-06 23:43
Thanks Christian. I actually didn't have indentLine installed so I decided to activate it and see if it fixed the issue.  While it's activated and there are no folds, the weird lines do indeed not appear with the indentLines in place, but if the file opens with the HTML folded, indentLines doesn't automatically show the lines, and the error persists.

https://user-images.githubusercontent.com/1163251/124679454-47af1e00-de79-11eb-9bd9-fe95e8c1107c.mp4

**Comment by ChristianChiarulli** [comment] 2021-07-07 00:21
Can you try `:TSUpdate`

**Comment by chuckmasucci** [comment] 2021-07-07 01:54
Running `:TSUpdate` removes the lines, but they come back when I move the cursor again.

**Comment by ChristianChiarulli** [comment] 2021-07-07 02:31
ok, so I narrowed it down to two things cursorline and treesitter, 

if you disable cursorline the problem goes away

If you `:TSBufDisable highlight` the problem also goes away, I'm pretty sure this is a treesitter problem.

**Comment by ChristianChiarulli** [comment] 2021-07-07 02:34
@chuckmasucci can confirm: https://github.com/nvim-treesitter/nvim-treesitter/issues/1506

**Comment by chuckmasucci** [comment] 2021-07-07 03:34
Ahh! Thanks so much for the assistance on this. Will subscribe to that issue for updates.

**Comment by theHamsta** [comment] 2021-07-09 18:00
You can solve it by out-commenting this line https://github.com/nvim-treesitter/nvim-treesitter/issues/1371#issuecomment-874327336

The reason is that those queries no longer regard our predicates that would check whether a tag is strike-through, bold etc,. There seems to be a behavior change in the tree-sitter library or Nvim.

**Comment by ChristianChiarulli** [comment] 2021-07-09 18:26
Thanks @theHamsta 

If no one beats me to it I plan on adding an autocommand that disables the cursorline in html files, should be less jarring.

**Comment by theHamsta** [comment] 2021-07-09 20:22
> If no one beats me to it I plan on adding an autocommand that disables the cursorline in html files, should be less jarring.

@ChristianChiarulli all the queries for tags get interpreted the wrong way. A workaround is just to out-comment the affected queries that I posted or just link `htmlTSStrikeThrough`, `htmlTSStrikeThrough` to something that has no highlight.

**Comment by rafamadriz** [comment] 2021-07-12 12:40
Closing this since the problem is with treesitter.

**Closed by rafamadriz** 2021-07-12 12:40 UTC
Labels: bug
