### ISSUE TITLE
[issue] eslint_d won't work in null-ls with the current implementation

### ISSUE THREAD

**Issue by Jacob87** [ChristianChiarulli/LunarVim#1101] opened 2021-07-25 23:54 UTC
#### This is how we are suppose to add the built-in `eslint_d` diagnostic in null-ls sources :
`null_ls.builtins.diagnostics.eslint.with({command = "eslint_d"})`

#### And when I put { "eslint_d" } in my lv-config under formatter.exe, this is how lunarvim currently adds it :
`null_ls.builtins.diagnostics.eslint_d`

which won't work.

#### Lunarvim version: Rolling

**Comment by dklymenk** [comment] 2021-07-26 05:34
Hello.

My understanding is that to set diagnostics provider you should set `lvim.lang.javascript.linters = {'eslint_d'}` and not `lvim.lang.javascript.formatter.exe = 'eslint_d'`, but I would assume that's what you meant because even with `lvim.lang.javascript.linters = {'eslint_d'}` or `lvim.lang.javascript.linters = 'eslint_d'` it doesn't work.

**Comment by Jacob87** [comment] 2021-07-26 05:39
@dklymenk Yes this is what I meant, thank you I corrected it in my example :)

**Comment by dklymenk** [comment] 2021-07-26 05:55
> according to the documentation

Can you please link to a piece of documentation you are referring to?

**Comment by PasiBergman** [comment] 2021-07-29 12:28
Submitted a PR  #1159 to fix this

**Comment by PasiBergman** [comment] 2021-07-29 13:31
Issue should be fixed in `rolling` branch/version.

**Comment by dklymenk** [comment] 2021-07-29 14:12
I confirm that the issue is fixed on `rolling` branch. Can't tell if it's actually using `eslint_d`, but feels a lot faster.

Thanks.

**Comment by abzcoding** [comment] 2021-07-29 14:16
Fixed via #1159

**Closed by abzcoding** 2021-07-29 14:16 UTC
