### ISSUE TITLE
Is there an autocomplete feature in lunarvim? If its there then it is not working for me? What might be the reason?

### ISSUE THREAD

**Issue by 3301n** [ChristianChiarulli/LunarVim#613] opened 2021-07-03 10:28 UTC
I need autocomplete for python, I have installed lsp for python using LspInstall python, but iam not getting autocompletion feautures. I was very handy

**Comment by nkoturovic** [comment] 2021-07-03 10:33
I think this is duplicate of #561
 - If this resolves problem for you close this issue.

**Comment by 3301n** [comment] 2021-07-03 10:52
Thats not the issue, Error signs are being shown when i import wrong moduels, All things are working out of the box except the autocomplete feature...........Here is my output when i type LspInfo:
`Configured servers: pyright, emmet_ls, efm
Neovim logs at: /home/kali/.cache/nvim/lsp.log

1 client(s) attached to this buffer: pyright

  Client: pyright (id 1)
  	root:      /home/kali/.config/nvim/lua
  	filetypes: python
  	cmd:       /home/kali/.local/share/nvim/lspinstall/python/node_modules/.bin/pyright-langserver --stdio
  	


1 active client(s): 

  Client: pyright (id 1)
  	root:      /home/kali/.config/nvim/lua
  	filetypes: python
  	cmd:       /home/kali/.local/share/nvim/lspinstall/python/node_modules/.bin/pyright-langserver --stdio
  	


Clients that match the filetype python:
  
  Config: pyright
  	cmd:               /home/kali/.local/share/nvim/lspinstall/python/node_modules/.bin/pyright-langserver --stdio
  	cmd is executable: True
  	identified root:   /home/kali/.config/nvim
  	custom handlers:   textDocument/publishDiagnostics
  
  Config: efm
  	cmd:               /home/kali/.local/share/nvim/lspinstall/efm/efm-langserver
  	cmd is executable: False. Please check your path and ensure the server is installed
  	identified root:   /home/kali/.config/nvim
 k`

**Comment by abzcoding** [comment] 2021-07-03 12:49
copy [lua/installer/lv-config.example.lua](https://github.com/ChristianChiarulli/LunarVim/blob/master/utils/installer/lv-config.example.lua) to `lv-config.lua` inside the `~/.config/nvim` folder, then close and start the `nvim` again and run `:PackerSync`
this should resolve it

**Comment by 3301n** [comment] 2021-07-03 16:59
When i run :PackerSync i am getting autocompletion about spellings only not getting from the language server. What should i do? to get autocompletion from my python language server?

**Comment by abzcoding** [comment] 2021-07-03 17:02
have you tried 
```
:LspInstall python
```
maybe @rebuilt can help

**Comment by 3301n** [comment] 2021-07-03 17:10
> have you tried
> 
> ```
> :LspInstall python
> ```
> 
> maybe @rebuilt can help

Yes i have tried the command. But still getting no autocompletion. Also the auto pairs also not working, For example when i put a ( i need another one automatically. Is there any way to enable it?

**Comment by rebuilt** [comment] 2021-07-03 17:10
I think we need more information. 

Please provide the results of the following:

```
# to see if there's a problem with the completion plugin
:checkhealth compe
# to show any errors printed to vim
:messages
# to see if the plugin is loaded
:PackerStatus

# from the command line.  To see if lsp is reporting errors
grep ERROR ~/.cache/nvim/lsp.log
```

**Comment by 3301n** [comment] 2021-07-03 17:12
SP[pyright]: Error NO_RESULT_CALLBACK_FOUND: {
  id = 5,
  jsonrpc = "2.0"
}LSP[pyright]: Error NO_RESULT_CALLBACK_FOUND: {
  id = 6,
  jsonrpc = "2.0"
}LSP[pyright]: Error NO_RESULT_CALLBACK_FOUND: {
  id = 7,
  jsonrpc = "2.0"
}LSP[pyright]: Error NO_RESULT_CALLBACK_FOUND: {
  id = 8,
  jsonrpc = "2.0"
}   

Getting this error when i close lunarvim after doing my work with python files

**Comment by 3301n** [comment] 2021-07-03 17:13
When i type grep ERROR  ~/.cache/nvim/lsp.log Iam getting this 


`[ ERROR ] 2021-07-03T16:48:00+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 16:48:00 efm-langserver: no configuration file\n2021/07/03 16:48:00 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-07-03T16:48:52+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 16:48:52 jsonrpc2 handler: sending response 2: jsonrpc2: connection is closed\n2021/07/03 16:48:52 efm-langserver: connections closed\n"
[ ERROR ] 2021-07-03T16:50:13+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 16:50:13 efm-langserver: no configuration file\n2021/07/03 16:50:13 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-07-03T16:50:30+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 16:50:30 jsonrpc2 handler: sending response 2: jsonrpc2: connection is closed\n2021/07/03 16:50:30 efm-langserver: connections closed\n"
[ ERROR ] 2021-07-03T16:54:35+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 16:54:35 efm-langserver: no configuration file\n2021/07/03 16:54:35 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-07-03T16:55:12+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 16:55:12 efm-langserver: no configuration file\n2021/07/03 16:55:12 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-07-03T16:55:12+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 16:55:12 efm-langserver: no configuration file\n2021/07/03 16:55:12 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-07-03T16:55:13+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 16:55:12 efm-langserver: no configuration file\n2021/07/03 16:55:12 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-07-03T16:55:13+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 16:55:12 efm-langserver: no configuration file\n2021/07/03 16:55:12 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-07-03T16:55:24+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 16:55:24 jsonrpc2 handler: sending response 2: jsonrpc2: connection is closed\n2021/07/03 16:55:24 efm-langserver: connections closed\n"
[ ERROR ] 2021-07-03T16:55:24+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 16:55:24 jsonrpc2 handler: sending response 2: jsonrpc2: connection is closed\n2021/07/03 16:55:24 efm-langserver: connections closed\n"
[ ERROR ] 2021-07-03T16:55:26+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 16:55:26 efm-langserver: no configuration file\n2021/07/03 16:55:26 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-07-03T16:55:42+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 16:55:42 jsonrpc2 handler: sending response 2: jsonrpc2: connection is closed\n2021/07/03 16:55:42 efm-langserver: connections closed\n"
[ ERROR ] 2021-07-03T16:55:44+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 16:55:44 efm-langserver: no configuration file\n2021/07/03 16:55:44 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-07-03T16:57:53+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 16:57:53 isort --quiet -: sh: 1: isort: not found\n\n"
[ ERROR ] 2021-07-03T16:57:53+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 16:57:53 yapf --quiet: sh: 1: yapf: not found\n\n"
[ ERROR ] 2021-07-03T16:58:26+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 16:58:26 jsonrpc2 handler: sending response 3: jsonrpc2: connection is closed\n"
[ ERROR ] 2021-07-03T16:58:26+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 16:58:26 efm-langserver: connections closed\n"
[ ERROR ] 2021-07-03T17:02:52+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 17:02:52 efm-langserver: no configuration file\n2021/07/03 17:02:52 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-07-03T17:04:16+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 17:04:16 jsonrpc2 handler: sending response 2: jsonrpc2: connection is closed\n2021/07/03 17:04:16 efm-langserver: connections closed\n"
[ ERROR ] 2021-07-03T17:24:33+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 17:24:33 efm-langserver: no configuration file\n2021/07/03 17:24:33 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-07-03T17:30:56+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 17:30:56 isort --quiet -: sh: 1: isort: not found\n\n"
[ ERROR ] 2021-07-03T17:30:56+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 17:30:56 yapf --quiet: sh: 1: yapf: not found\n\n"
[ ERROR ] 2021-07-03T17:31:00+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 17:31:00 isort --quiet -: sh: 1: isort: not found\n\n"
[ ERROR ] 2021-07-03T17:31:00+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 17:31:00 yapf --quiet: sh: 1: yapf: not found\n\n"
[ ERROR ] 2021-07-03T17:31:00+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 17:31:00 jsonrpc2 handler: sending response 4: jsonrpc2: connection is closed\n2021/07/03 17:31:00 efm-langserver: connections closed\n"
[ ERROR ] 2021-07-03T17:36:47+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 17:36:47 efm-langserver: no configuration file\n2021/07/03 17:36:47 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-07-03T17:38:22+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 17:38:22 jsonrpc2 handler: sending response 2: jsonrpc2: connection is closed\n2021/07/03 17:38:22 efm-langserver: connections closed\n"
[ ERROR ] 2021-07-03T17:38:25+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 17:38:25 efm-langserver: no configuration file\n2021/07/03 17:38:25 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-07-03T17:38:26+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 17:38:26 jsonrpc2 handler: sending response 2: jsonrpc2: connection is closed\n"
[ ERROR ] 2021-07-03T17:38:26+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 17:38:26 efm-langserver: connections closed\n"
[ ERROR ] 2021-07-03T22:24:37+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 22:24:37 efm-langserver: no configuration file\n2021/07/03 22:24:37 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-07-03T22:25:13+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 22:25:13 jsonrpc2 handler: sending response 51: jsonrpc2: connection is closed\n2021/07/03 22:25:13 efm-langserver: connections closed\n"
[ ERROR ] 2021-07-03T22:25:42+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 22:25:42 efm-langserver: no configuration file\n2021/07/03 22:25:42 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-07-03T22:25:44+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 22:25:44 jsonrpc2 handler: sending response 2: jsonrpc2: connection is closed\n"
[ ERROR ] 2021-07-03T22:25:44+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 22:25:44 efm-langserver: connections closed\n"
[ ERROR ] 2021-07-03T22:26:40+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 22:26:40 efm-langserver: no configuration file\n2021/07/03 22:26:40 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-07-03T22:28:14+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 22:28:12 jsonrpc2 handler: sending response 38: jsonrpc2: connection is closed\n2021/07/03 22:28:12 efm-langserver: connections closed\n"
[ ERROR ] 2021-07-03T22:29:12+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 22:29:12 efm-langserver: no configuration file\n2021/07/03 22:29:12 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-07-03T22:29:42+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 22:29:42 jsonrpc2 handler: sending response 3: jsonrpc2: connection is closed\n2021/07/03 22:29:42 efm-langserver: connections closed\n"
[ ERROR ] 2021-07-03T22:29:43+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:573 ]	"No callback found for server response id 2"
[ ERROR ] 2021-07-03T22:29:43+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp.lua:712 ]	"LSP[efm]"	"on_error"	{  code = "NO_RESULT_CALLBACK_FOUND",  err = {    id = 2,    jsonrpc = "2.0"  }}
[ ERROR ] 2021-07-03T22:29:55+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 22:29:55 efm-langserver: no configuration file\n2021/07/03 22:29:55 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-07-03T22:31:22+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 22:31:19 jsonrpc2 handler: sending response 34: jsonrpc2: connection is closed\n2021/07/03 22:31:19 efm-langserver: connections closed\n"
[ ERROR ] 2021-07-03T22:31:46+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 22:31:46 efm-langserver: no configuration file\n2021/07/03 22:31:46 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-07-03T22:32:31+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 22:32:30 jsonrpc2 handler: sending response 16: jsonrpc2: connection is closed\n2021/07/03 22:32:30 efm-langserver: connections closed\n"
[ ERROR ] 2021-07-03T22:34:12+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 22:34:12 efm-langserver: no configuration file\n2021/07/03 22:34:12 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-07-03T22:34:47+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 22:34:46 jsonrpc2 handler: sending response 22: jsonrpc2: connection is closed\n2021/07/03 22:34:46 efm-langserver: connections closed\n"
[ ERROR ] 2021-07-03T22:35:56+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 22:35:56 efm-langserver: no configuration file\n2021/07/03 22:35:56 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-07-03T22:36:17+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 22:36:14 jsonrpc2 handler: sending response 2: jsonrpc2: connection is closed\n2021/07/03 22:36:14 efm-langserver: connections closed\n"
[ ERROR ] 2021-07-03T22:36:38+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 22:36:38 efm-langserver: no configuration file\n2021/07/03 22:36:38 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-07-03T22:37:06+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 22:37:06 jsonrpc2 handler: sending response 3: jsonrpc2: connection is closed\n2021/07/03 22:37:06 efm-langserver: connections closed\n"
[ ERROR ] 2021-07-03T22:37:19+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 22:37:19 efm-langserver: no configuration file\n2021/07/03 22:37:19 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-07-03T22:38:42+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 22:38:42 jsonrpc2 handler: sending response 2: jsonrpc2: connection is closed\n2021/07/03 22:38:42 efm-langserver: connections closed\n"
[ ERROR ] 2021-07-03T22:40:45+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 22:40:45 efm-langserver: no configuration file\n2021/07/03 22:40:45 efm-langserver: reading on stdin, writing on stdout\n"
[ ERROR ] 2021-07-03T22:41:15+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/kali/.local/share/nvim/lspinstall/efm/efm-langserver"	"stderr"	"2021/07/03 22:41:15 jsonrpc2 handler: sending response 2: jsonrpc2: connection is closed\n2021/07/03 22:41:15 efm-langserver: connections closed\n"
[ ERROR ] 2021-07-03T22:41:16+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:573 ]	"No callback found for server response id 5"
[ ERROR ] 2021-07-03T22:41:16+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:573 ]	"No callback found for server response id 6"
[ ERROR ] 2021-07-03T22:41:16+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:573 ]	"No callback found for server response id 7"
[ ERROR ] 2021-07-03T22:41:16+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:573 ]	"No callback found for server response id 8"
[ ERROR ] 2021-07-03T22:41:16+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp.lua:712 ]	"LSP[pyright]"	"on_error"	{  code = "NO_RESULT_CALLBACK_FOUND",  err = {    id = 5,    jsonrpc = "2.0"  }}
[ ERROR ] 2021-07-03T22:41:16+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp.lua:712 ]	"LSP[pyright]"	"on_error"	{  code = "NO_RESULT_CALLBACK_FOUND",  err = {    id = 6,    jsonrpc = "2.0"  }}
[ ERROR ] 2021-07-03T22:41:16+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp.lua:712 ]	"LSP[pyright]"	"on_error"	{  code = "NO_RESULT_CALLBACK_FOUND",  err = {    id = 7,    jsonrpc = "2.0"  }}
[ ERROR ] 2021-07-03T22:41:16+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp.lua:712 ]	"LSP[pyright]"	"on_error"	{  code = "NO_RESULT_CALLBACK_FOUND",  err = {    id = 8,    jsonrpc = "2.0"  }}
`

**Comment by rebuilt** [comment] 2021-07-03 17:20
Can you try with a different small file to see if you get the same result?

**Comment by rebuilt** [comment] 2021-07-03 17:22
Also, I know there have been breaking changes in the history of neovim + compe development.  How old is your neovim version?   It might be worth upgrading it, to rule out incompatibilities.

**Comment by 3301n** [comment] 2021-07-03 17:35
> Also, I know there have been breaking changes in the history of neovim + compe development. How old is your neovim version? It might be worth upgrading it, to rule out incompatibilities.

my neovim version is 0.5 nightly , Is that the latest?

**Comment by rebuilt** [comment] 2021-07-03 17:37
What's 
```
nvim -v
```

**Comment by 3301n** [comment] 2021-07-03 17:39
NVIM v0.5.0-dev+nightly
Build type: Release

and some more................

**Comment by rebuilt** [comment] 2021-07-03 17:45
Hm.  I was hoping for a shaw hash, that would give us a date.  No worries, it's not hard to compile the newest .  Just follow the instructions on the wiki.

**Comment by abzcoding** [comment] 2021-07-14 07:41
try updating your neovim and using the latest `master` branch, if the problem still exists, feel free to reopen this issue

**Closed by abzcoding** 2021-07-14 07:41 UTC
